### ISSUE TITLE
Add support for listening to parent el scroll for grids

### ISSUE THREAD

**Issue by jmeas** [jmeas/marionette.sliding-view#14]

**Comment by jmeas** [comment]
Dear past self, is this not why you added [this method](https://github.com/jmeas/marionette.sliding-view/blob/master/src/marionette.sliding-view.js#L45-L51)?

**Comment by begizi** [comment]
I'd say this ones done already. That method makes it pretty straight forward to add a parent listener. :shipit:

**Comment by jmeas** [comment]
It's weird because I opened this after the latest releases, which also include this method. Ah well, gonna close for now.
