### ISSUE TITLE
Use rAF by default

### ISSUE THREAD

**Issue by jmeas** [jmeas/marionette.sliding-view#19]
'cause the internets are moving forward :earth_americas:

**Comment by begizi** [comment]
I started a branch with this. The only issue I'm having is trigging the rAF in the tests. Any thoughts?

**Comment by jmeas** [comment]
You'll prob. need to set `global.requestAnimationFrame` in [this file](https://github.com/jmeas/marionette.sliding-view/blob/master/test/setup/node.js). I doubt that JSDom comes with it.

**Comment by jmeas** [comment]
I'm going to close this as wontfix. After reading up on the proper use of rAF, I've decided it's too much boilerplate code to include in the library. I updated the inline comment to tell people what to do if they wish to change it.
