### ISSUE TITLE
Add forceRender option

### ISSUE THREAD

**Issue by jmeas** [jmeas/marionette.sliding-view#25]
SlickGrid has this. https://github.com/jmeas/marionette.sliding-view/pull/17 is an attempt to do this, but the option is placed on the view itself. Is that ok? Idk – I should think about it more.

**Comment by begizi** [comment]
What is the benefit of a force render option? The newly public update method should handle cases when a user wants to force a render. Correct?

**Comment by jmeas** [comment]
[In SlickGrid](https://github.com/mleibman/SlickGrid/blob/e004912b5ce29ac0d0cb04df50fe66db5e3af9ea/slick.grid.js#L2017-L2022), this appears to be an option that lets you completely turn off the delayed render. So rather than situationally forcing, it can make it so it **always** instantly renders.

I suppose the same functionality will be given in this library by exposing [the `isSmallChange` method](https://github.com/jmeas/marionette.sliding-view/issues/12#issuecomment-111840917). In other words:

```js
isSmallChange() { return true; }
```

Gonna close as wontfix.
