### ISSUE TITLE
Fire registerUpdateEvent after the view is attached to the dom

### ISSUE THREAD

**Issue by begizi** [jmeas/marionette.sliding-view#28]
This should make it cleaner to implement listening to a parent node as talked about in #14

**Comment by jmeas** [comment]
Ah, interesting thought! Are you thinking of the onAttach` event? I dig it.

**Comment by jmeas** [comment]
I implemented this in my app, and it works really well. Good idea, @begizi!

**Comment by jmeas** [comment]
I'm wondering if this should be left as-is, and the documentation just suggest using...

```js
registerUpdateEvent() {
  this.once('attach', () => {
    // lala
  });
}
```

What do you think, @begizi?

**Comment by jamesplease** [comment]
Gonna close this as wontfix and add a section to the docs explaining how to do this with the current API.
