### ISSUE TITLE
Add a default `isSmallChange` method that returns false

### ISSUE THREAD

**Issue by regexb** [jmeas/marionette.sliding-view#39]
The default action for `isSmallChange` should be false so it is not required to implement this method when the user doesn't want this feature.

**Comment by jamesplease** [comment]
It's [false by default already](https://github.com/jmeas/marionette.sliding-view/blob/master/src/marionette.sliding-view.js#L62), right?

**Comment by regexb** [comment]
You're right, It would return `undefined` from the execute helper. For some reason I thought if it wasn't defined it would throw an error, but that's not the case.

**Comment by regexb** [comment]
Actually, I'm even more wrong. You did define it as false. I completely missed it. :disappointed:

**Comment by jamesplease** [comment]
hahaha :stuck_out_tongue:
